# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

In [160]:
import pandas as pd
import numpy as np
import cleaning
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [161]:
insurance_df = pd.read_csv("insurance1.csv")
insurance_clean_df = insurance_df.copy()
insurance_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [162]:
# Your code here
insurance_clean_df = cleaning.clean_column_names(insurance_clean_df)
insurance_clean_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [163]:
#Gender: Unmodified values:
print(f"Original values: {insurance_clean_df['gender'].unique()}")
#Clean gender
insurance_clean_df = cleaning.fix_gender_mapping(insurance_clean_df)
#Check values after cleaning
print(f"Updated values: {insurance_clean_df['gender'].unique()}")
print(insurance_clean_df.info())

Original values: [nan 'F' 'M' 'Femal' 'Male' 'female']
Updated values: [nan 'F' 'M']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   object
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB
None

In [164]:
#State: Unmodified values:
print(f"Original values: {insurance_clean_df['state'].unique()}")
#Clean state
insurance_clean_df = cleaning.fix_state_mapping(insurance_clean_df)
#Check values after cleaning
print(f"Updated values: {insurance_clean_df['state'].unique()}")

Original values: ['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' 'Cali' 'AZ' 'WA'
 nan]
Updated values: ['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' nan]

In [165]:
#Bachelor: Unmodified values:
print(f"Original values: {insurance_clean_df['education'].unique()}")
#Clean
insurance_clean_df = cleaning.fix_education_value(insurance_clean_df)
#Check values after cleaning
print(f"Updated values: {insurance_clean_df['education'].unique()}")

Original values: ['Master' 'Bachelor' 'High School or Below' 'College' 'Bachelors' 'Doctor'
 nan]
Updated values: ['Master' 'Bachelor' 'High School or Below' 'College' 'Doctor' nan]

In [166]:
#Delete % in customer lifetime value
insurance_clean_df = cleaning.customer_lifetime_value(insurance_clean_df)
insurance_clean_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [167]:
#Sports car: Unmodified values:
print(f"Original values: {insurance_clean_df['vehicle_class'].unique()}")
#Clean
insurance_clean_df = cleaning.fix_vehicle_mapping(insurance_clean_df)
#Check values after cleaning
print(f"Updated values: {insurance_clean_df['vehicle_class'].unique()}")

Original values: ['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury SUV' 'Sports Car'
 'Luxury Car' nan]
Updated values: ['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury' nan]

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [168]:
# Customer lifetime to numeric:
print(f"Customer_lifetime_value column is {insurance_clean_df['customer_lifetime_value'].dtype}")
insurance_clean_df = cleaning.convert_column_type_to_float(insurance_clean_df)

Customer_lifetime_value column is object
Customer_lifetime_value column is now float64

In [169]:
#Number of open complaints
insurance_clean_df = cleaning.extract_open_complaints(insurance_clean_df)

In [170]:
insurance_clean_df.sample(10)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
645,JA41698,Nevada,M,Bachelor,309953.80,0.0,102.0,5.0,Corporate Auto,SUV,862.762957
3714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,QH19450,California,F,High School or Below,255817.82,0.0,72.0,0.0,Corporate Auto,Four-Door Car,345.600000

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [171]:
# Check rows with all nulls
print(insurance_clean_df.isnull().sum())
#Delete rows with all null values
insurance_clean_df = cleaning.drop_all_null_rows(insurance_clean_df)
# Check rows with all nulls
print(f"rows with all values in null after cleaning {insurance_clean_df.isnull().sum()}")

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64
Found 2937 rows with all null values
Shape after dropping all-null rows: (1071, 11)
rows with all values in null after cleaning customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [172]:
#Now as can be seen above, gender has a lot of null values, customer_lifetime_value only 3. Let's have a look:
#First Gender
gender_distribution = insurance_clean_df["gender"].value_counts(normalize=True) * 100
print("\nGender distribution (%):")
print(gender_distribution.round(2))

Gender distribution (%):
gender
F    52.62
M    47.38
Name: proportion, dtype: float64

In [173]:
# 1. Calculate the mode
mode_gender = insurance_clean_df["gender"].mode()[0]
print(f"Most common value (mode): {mode_gender}")

# 2. Count before filling
missing_before = insurance_clean_df["gender"].isna().sum()
print(f"Found {missing_before} missing values")

# 3. Fill
insurance_clean_df["gender"] = insurance_clean_df["gender"].fillna(mode_gender)

# 4. Verify after
print(f"Missing values after filling: {insurance_clean_df['gender'].isna().sum()}")
print(f"Filled {missing_before} missing values with '{mode_gender}'")

Most common value (mode): F
Found 117 missing values
Missing values after filling: 0
Filled 117 missing values with 'F'

In [174]:
#Now customer_lifetime_value
print("Mean",insurance_clean_df["customer_lifetime_value"].mean())
print("STD",insurance_clean_df["customer_lifetime_value"].std())
print("Median",insurance_clean_df["customer_lifetime_value"].median())

Mean 793690.2593445693
STD 643478.4102780645
Median 588174.235

In [175]:
#As the mean is much higher than the median it means that the distribution is not normal. 
# The best approach would be to use the median here to not alter the distribution
median = insurance_clean_df["customer_lifetime_value"].median()
missing_before2 = insurance_clean_df["customer_lifetime_value"].isna().sum()
print(f"The number of missing values for customer_lifetime_value is: {missing_before2}")

#Fill
insurance_clean_df["customer_lifetime_value"] = insurance_clean_df["customer_lifetime_value"].fillna(median)
print(f"Missing values after filling: {insurance_clean_df['customer_lifetime_value'].isna().sum()}")
print(f"Filled {missing_before2} missing values with '{median}'")

The number of missing values for customer_lifetime_value is: 3
Missing values after filling: 0
Filled 3 missing values with '588174.235'

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [184]:
# Count duplicates
duplicate_count = insurance_clean_df["customer"].duplicated().sum()
print(f"Number of duplicate customer IDs: {duplicate_count}")

#There arent duplicaded customers, so the data is clean

Number of duplicate customer IDs: 0

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here